### PR TITLE
PNPM support added

### LINKED ISSUE #5: Support pnpm
Its faster than `yarn` & `npm` 🚀

### PR DESCRIPTION
**Pull request by deadcoder0904**
Close #5

### CODE REVIEW

**Comment by tiaanduplessis** [comment]
Thanks for the PR 👍

**Comment by deadcoder0904** [comment]
@tiaanduplessis New version is not published on `npm`, right ❓

**Comment by tiaanduplessis** [comment]
Not yet. Will publish soon 👍

**Comment by deadcoder0904** [comment]
Cool whenever u get time

**Pull request merged**
